backend:
  name: git-gateway
  repo: mto37/mto37.github.io # 替换为您的 GitHub 仓库
  branch: master # 指定 Decap CMS 提交内容的分支
  identity_url: https://auth.decapbridge.com/sites/af0d75ec-b928-41df-9257-3fd85da11a84
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

media_folder: "static/images/uploads" # 指定媒体文件上传的路径
public_folder: "/images/uploads"

collections:
  - name: "blog" # 集合的名称
    label: "Blog" # 在 CMS 界面中显示的标签
    folder: "content/posts" # Hugo 博文所在的文件夹
    create: true # 允许在 CMS 中创建新文件
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # 文件名的格式
    fields: # 定义内容字段
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
# Use DecapBridge auth (required)

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://mto37.github.io
