# GitHub 仓库后端设置
backend:
  name: github
  repo: mto37/mto37.github.io # ‼️ 必须修改成您的：GitHub用户名/仓库名
  branch: master # ‼️ 您的源文件所在的主分支，通常是 main 或 master

# 媒体文件（如图片）的存储位置
media_folder: "static/images/uploads" # 建议值：上传的图片将存放在这里
public_folder: "/images/uploads" # 建议值：网站上访问图片的路径

# 定义您要管理的内容集合（这里是“文章”）
collections:
  - name: "post" # 内部标识，保持不变即可
    label: "文章" # 在后台管理界面上显示的名称
    folder: "content/posts" # ‼️ 存放文章 Markdown 文件的目录，请确保路径正确
    create: true # 允许创建新文章
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # 文章保存的文件名格式
    fields: # 定义文章的字段，这些会变成您写作界面上的输入框
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "标签", name: "tags", widget: "list", required: false}
      - {label: "草稿", name: "draft", widget: "boolean", default: false}
      - {label: "正文", name: "body", widget: "markdown"}
