backend:
  name: github
  # ！！！【【【 极其重要，必须修改 】】】 ！！！
  repo: mto37/mto37.github.io # 替换成你自己的 GitHub 用户名和仓库名
  branch: master

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "作者", name: "author", widget: "string", required: false }
      - { label: "草稿", name: "draft", widget: "boolean", default: true }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "正文", name: "body", widget: "markdown" }
