# .github/workflows/gh-pages.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 当 main 分支有 push 时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # 获取主题 submodule
          fetch-depth: 0    # 获取所有 history

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify # 运行 hugo 构建命令

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Hugo 生成的静态文件目录
